#!/usr/bin/python3
# coding: utf-8




 #importing required libraries

import pandas as pd
import csv
from collections import defaultdict
import csv
from collections import defaultdict


#cleaning of datasets using Dictionery and List

"""
disease_list = []    #empty list

def return_list(disease):
    disease_list = []
    match = disease.replace('^','_').split('_')
    ctr = 1
    for group in match:
        if ctr%2==0:
            disease_list.append(group)
        ctr = ctr + 1

    return disease_list    #fetched Disease-List



#reading of Uncleaned Data

with open("/home/mudit/practice/Scraped-Data/dataset_uncleaned.csv") as csvfile:
    reader = csv.reader(csvfile)
    disease=""
    weight = 0
    disease_list = []
    dict_wt = {}
    dict_=defaultdict(list)
    for row in reader:
        if row[0]!="\xc2\xa0" and row[0]!="":
            disease = row[0]
            disease_list = return_list(disease)    #substituting values
            weight = row[1]

        if row[2]!="\xc2\xa0" and row[2]!="":
            symptom_list = return_list(row[2])

            for d in disease_list:
                for s in symptom_list:
                    dict_[d].append(s)
                dict_wt[d] = weight     #included weights in symptom list


#writing Data as csv file after cleaning

with open("/home/mudit/practice/Scraped-Data/dataset_clean.csv","w") as csvfile:
    writer = csv.writer(csvfile)
    for key,values in dict_.items():
        for v in values:
            #key = str.encode(key)
            key = str.encode(key).decode('utf-8').strip()   #encoding  by UTF-8
            #v = v.encode('utf-8').strip()
            #v = str.encode(v)
            writer.writerow([key,v,dict_wt[key]])               
                
    #print (dict_)



#reading of cleaned dataset

data = pd.read_csv("/home/mudit/practice/Scraped-Data/dataset_clean.csv",encoding ="ISO-8859-1")
print(data)





data.iloc[0,:]




data.to_csv("/home/mudit/practice/Scraped-Data/dataset_clean.csv",index=False)


#distinguished between Disease and Symptom

slist = []
dlist = [] 
with open("/home/mudit/practice/Scraped-Data/nodetable.csv","w") as csvfile:
    writer = csv.writer(csvfile)

    for key,values in dict_.items():
        for v in values:
            if v not in slist:
                writer.writerow([v,v,"symptom"])
                slist.append(v)
        if key not in dlist:
            writer.writerow([key,key,"disease"])
            dlist.append(key)



"""

